<?php


/**
 * Implementation of hook_permission().
 */
function chat_permission() {
  return array(
    'access chat' => array(
      'title' => t('Access Chat'),
      'description' => t('Allow access to the chat subsystem.'),
    ),
  );
}


/**
 * Implementation of hook_menu().
 */
function chat_menu() {
  $items = array();

  $items['chat'] = array(
    'title'            => 'Chat',
    'access arguments' => array('access chat'),
    'page callback'    => 'chat_page',
    'type'             => MENU_CALLBACK,
  );

  return $items;
}


/**
 * Implementation of hook_theme().
 */
function chat_theme() {
  return array(
    'chat' => array(
      'template' => 'chat',
      'arguments' => array('username' => NULL),
    ),
  );
}


/**
 * Page callback for /chat menu item.
 */
function chat_page() {
  global $user;
  
  return theme('chat', array('user' => $user, 'users' => online_users()));
}

function online_users(){
    global $user;

    $query = db_select('chat_messages', 'm');
    $db_or = db_or();
    $db_or->condition('m.sender', $user->uid);

    $db_or->condition('m.receiver', $user->uid);
    $query->condition($db_or);

    $query->join('users', 'u', 'u.uid = m.receiver OR u.uid = m.sender');
    $query->condition('u.uid', $user->uid, '!=');

    $query->groupBy('u.uid');
    $query->fields('u', array('uid'));

    $query->fields('m', array('id', 'message', 'sender', 'receiver'));
    $query->fields('u', array('name', 'mail'));

    $query->addExpression('MAX(timestamp)');
    $query->orderBy('m.timestamp', 'DESC')
            ->range(0, 30);
//echo '<pre>'; print_r($query->execute()->fetchAll()); exit;
    return $query->execute()->fetchAll();
}

